package com.mk3.chatapp.enums;

public enum WebSocketMessageType {
    NEW_MESSAGE,
    POPULARITY_UPDATE,
    LEADERBOARD_UPDATE_ONLINE,
    LEADERBOARD_UPDATE_ACTIVE,
    BAN_USER,
    BAN_USER_CHAT_NOTIFICATION,
    WARN_USER,
    DELETE_MESSAGE,
    ROLE_UPDATE_NOTIFICATION,
    MESSAGE_REACTION_UPDATE,
    MESSAGE_EDIT,
    REPORT_NOTIFICATION,
    CHATROOM_ARCHIVED,
    CHATROOM_UNARCHIVED,
    MESSAGE_SENDING_AVAILABILITY_UPDATE,
    PRIVATE_NEW_MESSAGE,
    PRIVATE_MESSAGE_EDIT,
    PRIVATE_MESSAGE_DELETE,
    PROMOTED_MESSAGE_UPDATE,
    ID_VERIFICATION_REQUIRED,
    ID_VERIFICATION_RESULT
}
